### ISSUE TITLE
not updateting alll

### ISSUE THREAD

**Issue by sschouten** [Dielee/volvo2mqtt#121]
**Describe the bug**
The addon can not fetch al data any more.

**To Reproduce**:<br>
allways when i sync
Before the doors windows enzzz was syncing right but the last view days it is not ?
Version 1.8.8
Hass:
Core
2023.11.1
Supervisor
2023.11.0
Operating System
11.1
Frontend
20231030.1

INFO: Success! Last Data Update is supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Success! Active schedules is supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Window Front Left is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Window Front Right is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Window Rear Left is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Window Rear Right is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Door Front Left is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Door Front Right is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Door Rear Left is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Door Rear Right is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Tailgate is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Engine Hood is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Tank Lid is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Sunroof is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Success! Air Conditioning is supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Failed, Lock state is unfortunately not supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Success! Force Update Data is supported by your vehicle.
Nov 09 16:15:01 volvo2mqtt [106] - INFO: Success! Location is supported by your vehicle.

**Version info**:<br>
home assistant addon

**Comment by Dielee** [comment]
Please enable debug and send some logs

**Comment by sschouten** [comment]
[volvo2mqtt.log](https://github.com/Dielee/volvo2mqtt/files/13309891/volvo2mqtt.log)
tnx

**Comment by Dielee** [comment]
Please list all sensors which are not updating anymore

**Comment by thomasddn** [comment]
(I deleted my comment in the other issue, because this issue is exactly the same as I have.)

At least these entities are not working anymore:
* service_warning_status
* km_to_service
* months_to_service
* lock_status (+ command)

Maybe others as well, but I don't have the full list anymore because I deleted all MQTT topics and restarted the addon in the hope it would fix things. Only the working entities were created again, so I could only list the entities that I'm using in a dashboard.

If it helps, here is a list of entities still working as a screenshot.

<details><summary>Entities</summary>
<p>

![image](https://github.com/Dielee/volvo2mqtt/assets/11554546/fa92fb38-0c39-4a04-8544-598c6d237052)

</p>
</details>

**Comment by sschouten** [comment]
-Distance to Service
-Door Front
-Door Rear
-Engine Hood
-Engine State
-Months to Service
-Service warning status
-Service warning status
-Sunroof
-Tailgate
-Tank Lid
-Tire Front left and the others

**Comment by Dielee** [comment]
Should be fixed by version v1.8.9

**Comment by joanyh77** [comment]
Works much better with v1.8.9. Big thx!! Unfortunately still get this for battery.

Nov 09 19:09:09 volvo2mqtt [1] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.
Nov 09 19:09:09 volvo2mqtt [1] - ERROR: API Call failed. Status Code: 404. Error: { "statusCode": 404, "message": "Resource not found" }
Nov 09 19:09:09 volvo2mqtt [1] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.

**Comment by Dielee** [comment]
> Works much better with v1.8.9. Big thx!! Unfortunately still get this for battery.
> 
> Nov 09 19:09:09 volvo2mqtt [1] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle. Nov 09 19:09:09 volvo2mqtt [1] - ERROR: API Call failed. Status Code: 404. Error: { "statusCode": 404, "message": "Resource not found" } Nov 09 19:09:09 volvo2mqtt [1] - INFO: Failed, Battery Charge Level is unfortunately not supported by your vehicle.

This happens some times, if the issue persist, please open a new ticket.
